### ISSUE TITLE
Add notes via commands

### ISSUE THREAD

**Issue by IAmFletcher** [clarkio/stream-note-taker#1]
For example: Someone in chat calls !`command_name` followed by a description. It automatically adds a marker, the name of the user, and the description to the relevant section.

The streamer should be able to specify the commands, the section titles, and who has permission to call those commands.

Potential uses: !today, !task, !quote

**Comment by clarkio** [comment]
We've made progress on this that allows viewers to use `!mark` in chat and that will result in the following written to the timestamps table: `| 00:00:00 | <message> (created by <username>) |\n`. 

I think the only thing missing from your suggestion is the permissions. Anyone can add these markers at the moment. I kind of want to keep it like that so that we can get as much help as possible in making relevant timestamp markers. What do you think?

If you agree I think we can close this issue and/or open a separate one for the permissions part.

**Comment by IAmFletcher** [comment]
Sweet! :raised_hands: 

I think there should be permissions, even just the ability to remove an individual from being able to !line/!mark in chat. However, yeah, that's a separate issue.

**Comment by clarkio** [comment]
We've also now added the `!note` command but still need to implement some type of permissions restriction to them all. Thanks again for this suggestion and we'll consider this issue closed.
